[workspace]
resolver = "3"
members = [
    "algo", 
    "cli",
    "webgraph",
]

[workspace.dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
epserde = "0.8.0"
dsi-bitstream = "0.5.0"
dsi-progress-logger = "0.8.1"
log = "0.4.22"
sux = "0.7.2"
common_traits = "0.11.2"
lender = "0.3.1"

[profile.release]
opt-level = 3            # like --release
lto = "fat"              # Full LTO
overflow-checks = false  # Disable integer overflow checks.
debug = true             # Include debug info.
debug-assertions = false # Enables debug assertions.
codegen-units = 1        # slower compile times, but maybe better perf

[profile.bench]
opt-level = 3            # like --release
lto = "fat"              # Full LTO
overflow-checks = false  # Disable integer overflow checks.
debug = true             # Include debug info.
debug-assertions = false # Enables debug assertions.
codegen-units = 1        # slower compile times, but maybe better perf
