name: LLP Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Adding baremetal arm target
        run: rustup target add aarch64-unknown-none
      - name: Copy Cnr-2000 to a new directory
        run: mkdir llp && cp tests/data/cnr-2000.graph ./llp && cp tests/data/cnr-2000.properties ./llp
      - name: Run test pipeline on cnr-2000
        run: ./pipeline.sh ./llp/cnr-2000
